version: '3.6'

services:
  web:
    image: 'gitlab/gitlab-ce:latest'
    container_name: gitlab-web
    restart: always
    healthcheck:
      test: curl -k --fail https://localhost/-/health || exit 1 
      interval: 30s
      timeout: 3s
      retries: 5
      start_period: 2m
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # Add any other gitlab.rb configuration here, each on its own line
        external_url 'https://gitlab.example.com'

        #Potential security risks
        gitlab_rails['monitoring_whitelist'] = ['0.0.0.0/0']
        gitlab_rails['initial_root_password'] = '28w4hHGxg6hITqtK50TfWVbI+XmaFN7hHDu3Qz4MVv0='
        gitlab_rails['initial_shared_runners_registration_token'] = 't0ken'
        
        #Firmados con mi propio CertificateAuthority
        nginx['ssl_certificate'] = "/etc/ssl/certs/gitlab/server.crt"
        nginx['ssl_certificate_key'] = "/etc/ssl/certs/gitlab/server.key"
        nginx['ssl_protocols'] = "TLSv1.1 TLSv1.2"
    ports:
      - '80:80'
      - '443:443'
      - '2222:22'
    volumes:
      - './gitlab_app/config:/etc/gitlab'
      - './gitlab_app/logs:/var/log/gitlab'
      - './gitlab_app/data:/var/opt/gitlab'
      - './ssl:/etc/ssl/certs/gitlab'      
    networks:
      dev-net:
        aliases:
          - gitlab.example.com
    shm_size: '256m'

  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    container_name: gitlab-runner
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./gitlab-runner/config:/etc/gitlab-runner
      - './ssl/server.crt:/etc/gitlab-runner/certs/ca.crt:ro'
    depends_on:
      web:
        condition: service_healthy
    networks: 
      - dev-net

  register-gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    volumes:
      - ./gitlab-runner/config:/etc/gitlab-runner
      - './ssl/server.crt:/etc/gitlab-runner/certs/ca.crt:ro'
    command:
      - register
      - --non-interactive
      - --locked=false
      - --run-untagged
      - --name=GitLab Runner
      - --tag-list=docker,dind
      - --executor=docker
      - --docker-image=docker:stable
      - --docker-volumes=/var/run/docker.sock:/var/run/docker.sock
      - --docker-network-mode=dev-net
    environment:
      - "CI_SERVER_URL=https://gitlab.example.com/"
      - "REGISTRATION_TOKEN=t0ken"
    depends_on:
      web:
        condition: service_healthy
    networks: 
      - dev-net
networks:
  dev-net:
    name: dev-net
