version: '3.6'

services:
  web:
    image: 'gitlab/gitlab-ce:15.11.0-ce.0'
    container_name: gitlab-web
    restart: always
    healthcheck:
      test: curl -k --fail https://localhost/-/health || exit 1 
      interval: 30s
      timeout: 3s
      retries: 5
      start_period: 2m
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # Add any other gitlab.rb configuration here, each on its own line
        external_url 'https://gitlab.example.com'

        #Potential security risks
        gitlab_rails['monitoring_whitelist'] = ['0.0.0.0/0']
        gitlab_rails['initial_root_password'] = '28w4hHGxg6hITqtK50TfWVbI+XmaFN7hHDu3Qz4MVv0='
        gitlab_rails['initial_shared_runners_registration_token'] = 't0ken'

        #registry
        gitlab_rails['registry_enabled'] = true
        gitlab_rails['registry_host'] = "registry.example.com"
        gitlab_rails['registry_port'] = "5001"
        gitlab_rails['registry_api_url'] = "https://registry.example.com:5001"

        #Defino acá el certificado CA porque en trusted-certs se seguía borrando, y en origen rompe todo
        gitlab_rails['env'] = {"SSL_CERT_FILE" => "/etc/ssl/certs/gitlab/rootCA.crt"}
        
        #Firmados con mi propio CertificateAuthority
        nginx['ssl_certificate'] = "/etc/ssl/certs/gitlab/server.crt"
        nginx['ssl_certificate_key'] = "/etc/ssl/certs/gitlab/server.key"
        nginx['ssl_protocols'] = "TLSv1.1 TLSv1.2"
    ports:
      - '80:80'
      - '443:443'
      - '2222:22'
    volumes:
      - './gitlab_app/config:/etc/gitlab'
      - './gitlab_app/logs:/var/log/gitlab'
      - './gitlab_app/data:/var/opt/gitlab'
      - './ssl:/etc/ssl/certs/gitlab:ro'
    networks:
      dev-net:
        aliases:
          - gitlab.example.com
    shm_size: '256m'

  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    container_name: gitlab-runner
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./gitlab-runner/config:/etc/gitlab-runner
      - './ssl/server.crt:/etc/gitlab-runner/certs/ca.crt'
    depends_on:
      web:
        condition: service_healthy
    networks: 
      - dev-net

  register-gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    container_name: register-runner
    volumes:
      - ./gitlab-runner/config:/etc/gitlab-runner
      - './ssl/server.crt:/etc/gitlab-runner/certs/ca.crt:ro'
    command:
      - register
      - --non-interactive
      - --locked=false
      - --run-untagged
      - --name=GitLab Runner
      - --tag-list=docker,dind
      - --executor=docker
      - --docker-image=docker:stable
      - --docker-volumes=/var/run/docker.sock:/var/run/docker.sock
      - --docker-network-mode=dev-net
    environment:
      - "CI_SERVER_URL=https://gitlab.example.com/"
      - "REGISTRATION_TOKEN=t0ken"
    depends_on:
      web:
        condition: service_healthy
    networks: 
      - dev-net

  registry:
    image: registry:2
    restart: always
    container_name: registry
    hostname: 'registry.example.com'
    environment:
      - REGISTRY_HTTP_ADDR=0.0.0.0:5001
      - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/server.crt
      - REGISTRY_HTTP_TLS_KEY=/certs/server.key
    ports:
      - 5001:5001
    volumes:
      - './ssl/:/certs/:ro'
      - ./gitlab-registry/:/var/lib/registry
    networks:
      dev-net:
        aliases:
          - registry.example.com

networks:
  dev-net:
    name: dev-net